### PR TITLE
Enable checkstyle/findbugs/pmd in travis and fix all occurring bugs

### PR DESCRIPTION
**Pull request by mwolting**
Travis will now fail if there are errors in Checkstyle, FindBugs and PMD. All of those have been cleaned up.

### CODE REVIEW

**Comment by NilsHullegien** [comment]
Looks good!

**Comment by NilsHullegien** [comment]
If anyone else agrees, could that person please merge this branch into the master?

**Comment by mwolting** [comment]
@levilime 
@marcelkuipers 
@hmyeh
@anyone ?

**Comment by levilime** [comment]
I can see a few checkstyle errors in MainGameScreen and Player

**Comment by levilime** [comment]
Both lines longer than 80... I wouldn't mind normally at all but please fix them otherwise we'll have a failing master after this merge... :panda_face: :train:

**Comment by levilime** [comment]
Ah I see you have increased the line length... will merge :shipit:

**Comment by levilime** [comment]
@mwolting now it's key to fix the master again, but I guess fail with checkstyle is for the better :partly_sunny:  :sun_with_face:

**Pull request merged**
