### PR TITLE
Game over screen

### PR DESCRIPTION
**Pull request by marcelkuipers**
When the player falls into a void he will be presented with a game over screen. From this screen he can either go back to the main menu or start the game over again.

### CODE REVIEW

**Comment by mwolting** [comment]
Lookin' good

**Comment by levilime** [comment]
I think the Gamover Screen code shouldn't live in the MainGameScreen.class, I think it would be nice if it had it's own class, the MainGameScreen won't grow so much.

**Comment by levilime** [comment]
Functionally it works for me. I agree with the merge when the above thing about seperating gameover code from maingamescreen is done.

**Comment by NilsHullegien** [comment]
I agree on merging

**Comment by levilime** [comment]
fixes #10

**Comment by levilime** [comment]
fixes #11

**Comment by levilime** [comment]
fixes #29

**Comment by levilime** [comment]
fixes #13

**Pull request merged**
