### PR TITLE
Remplement physics operations through the Strategy pattern

### PR DESCRIPTION
**Pull request by mwolting**
There are now two different physics strategies - one for the player and one for static objects. 

<feature

### CODE REVIEW

**Comment by NilsHullegien** [comment]
Nice addition to the project for this sprint.
Code looks good. 

<review

**Comment by mwolting** [comment]
I'm pretty sure that that's a mistake in IntelliJ's autoformatter.

**Comment by NilsHullegien** [comment]
Looks good now!

**Comment by levilime** [comment]
Cool implementation, this way physics logic for different objects is far more organized. I agree with this merge.

**Comment by NilsHullegien** [comment]
Thanks levilime for making the bg of the images transparant, nice addition!

**Pull request merged**
