### PR TITLE
Fixed spawn kills by shooting obstacle<feature

### PR DESCRIPTION
**Pull request by NilsHullegien**
Fix the spawn kills by shooting obstacle
<feature

### CODE REVIEW

**Comment by levilime** [comment]
But this means you'll have a really uneventful level, is not a problem if it only appears at the start. But if it appears more, or even a few times next to each other than the game becomes less active

**Comment by NilsHullegien** [comment]
This fix is only for the first game slice the player spawns on, after the first gameSlice everything remains the same.

**Comment by mwolting** [comment]
Nicely found, looking good

**Comment by levilime** [comment]
Will close this because by request this fix is made in #108

**Comment by levilime** [comment]
Will close this because by request this fix is made in #108

**Pull request closed without merging**
