### PR TITLE
Blackhole

### PR DESCRIPTION
**Pull request by levilime**
Multiple levels, gradually becoming harder gameplay

### CODE REVIEW

**Comment by mwolting** [comment]
Nice addition to the gameplay. (Would it maybe be a good idea to fix the gaps between platforms in this branch too? Seems applicable to its purpose)

**Comment by levilime** [comment]
Sure I'll put that one in too

**Comment by mwolting** [comment]
Alright, great

**Comment by NilsHullegien** [comment]
Code looks good, indeed a nice addition to the gameplay.

<review

**Pull request merged**
